=== trair18/BankDeposits/data/banks.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/banks"
        xmlns:tns="http://www.example.com/banks"
        elementFormDefault="qualified">

    <element name="bank" type="tns:Bank" abstract="true"></element>
    <element name="commercial_bank" type="tns:CommercialBank" substitutionGroup="tns:bank"></element>
    <element name="central_bank" type="tns:CentralBank" substitutionGroup="tns:bank"></element>

    <element name="banks">
        <complexType>
            <sequence>
                <element ref="tns:bank" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Bank">
        <sequence>
            <element name="deposit"
                     type="tns:Deposit"
                     minOccurs="1"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="CommercialBank">
        <complexContent>
            <extension base="tns:Bank">
                <attribute name="name" type="string" use="required"/>
                <attribute name="branches_number" type="positiveInteger" use="optional"/>
            </extension>
        </complexContent>
    </complexType>
    
    <complexType name="CentralBank">
        <complexContent>
            <extension base="tns:Bank">
                <attribute name="country" type="string" use="required" />
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="AccountID">
        <restriction base="ID">
            <pattern value="([a-zA-Z])[a-zA-Z0-9]{1,15}"/>
        </restriction>
    </simpleType>

    <complexType name="Deposit">
        <sequence>
            <element name="country" type="string"/>
            <element name="type">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="poste restance"></enumeration>
                        <enumeration value="express"></enumeration>
                        <enumeration value="calculated"></enumeration>
                        <enumeration value="camulative"></enumeration>
                        <enumeration value="saving"></enumeration>
                        <enumeration value="metal"></enumeration>
                    </restriction>
                </simpleType>
            </element>
            <element name="depositor" type="string"/>
            <element name="account_ID" type="tns:AccountID"/>
            <element name="amount_on_deposit" type="positiveInteger"/>
            <element name="profitability" type="double"/>
            <element name="time_constraints" type="dateTime"/>
        </sequence>
    </complexType>

</schema>

=== trair18/BankDeposits/data/banks.xml
<banks  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.example.com/banks"
        xsi:schemaLocation="banks.xsd ../data/banks.xsd">

    <commercial_bank name="Bank Moscow-Minsk" branches_number="6">
        <deposit>
            <country>Belarus</country>
            <type>metal</type>
            <depositor>Ivanov Ivan</depositor>
            <account_ID>q1</account_ID>
            <amount_on_deposit>450</amount_on_deposit>
            <profitability>12.5</profitability>
            <time_constraints>2018-05-30T10:28:44</time_constraints>
        </deposit>
        <deposit>
            <country>Russia</country>
            <type>express</type>
            <depositor>Petrov Petr</depositor>
            <account_ID>q2</account_ID>
            <amount_on_deposit>250</amount_on_deposit>
            <profitability>2.5</profitability>
            <time_constraints>2018-06-13T15:30:12</time_constraints>
        </deposit>
    </commercial_bank>

    <commercial_bank name="Belinvestbank">
        <deposit>
            <country>Belarus</country>
            <type>calculated</type>
            <depositor>Sidorov Semen</depositor>
            <account_ID>q3</account_ID>
            <amount_on_deposit>1000</amount_on_deposit>
            <profitability>3.5</profitability>
            <time_constraints>2017-12-24T21:23:00</time_constraints>
        </deposit>
        <deposit>
            <country>Belarus</country>
            <type>saving</type>
            <depositor>Saberov John</depositor>
            <account_ID>q4</account_ID>
            <amount_on_deposit>1450</amount_on_deposit>
            <profitability>4.5</profitability>
            <time_constraints>2018-02-20T06:00:00</time_constraints>
        </deposit>
    </commercial_bank>

    <central_bank country="Belarus">
        <deposit>
            <country>Belarus</country>
            <type>camulative</type>
            <depositor>Gonchar Vasili</depositor>
            <account_ID>q5</account_ID>
            <amount_on_deposit>700</amount_on_deposit>
            <profitability>2.5</profitability>
            <time_constraints>2018-01-10T18:00:00</time_constraints>
        </deposit>
        <deposit>
            <country>USA</country>
            <type>poste restance</type>
            <depositor>Onegin Evgen</depositor>
            <account_ID>q6</account_ID>
            <amount_on_deposit>4450</amount_on_deposit>
            <profitability>3.5</profitability>
            <time_constraints>1883-03-20T09:00:00</time_constraints>
        </deposit>
    </central_bank>

    <central_bank country="Russia">
        <deposit>
            <country>Canada</country>
            <type>poste restance</type>
            <depositor>Bulkin Vasya</depositor>
            <account_ID>q7</account_ID>
            <amount_on_deposit>730</amount_on_deposit>
            <profitability>2.3</profitability>
            <time_constraints>2018-01-10T12:00:00</time_constraints>
        </deposit>
        <deposit>
            <country>Russia</country>
            <type>poste restance</type>
            <depositor>Harry Potter</depositor>
            <account_ID>q8</account_ID>
            <amount_on_deposit>4450</amount_on_deposit>
            <profitability>3.4</profitability>
            <time_constraints>2001-09-20T10:00:00</time_constraints>
        </deposit>
    </central_bank>

</banks>
